version: '3.8'

volumes:
    postgres_data:

services:
    api:
        build: .
        volumes:
            - ./:/code
        ports:
            - 8030:80
        env_file:
            - .env
        depends_on:
            db:
                condition: service_healthy
    db:
        image: postgres:12.0-alpine
        ports:
            - "49166:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 7s
            timeout: 5s
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=senha
            - POSTGRES_DB=bravo
            - DATABASE_URL=postgresql://postgres:senha@db/bravo
